Portal 1426/react code cleanup
CDCgov/data-exchange-portal pull request #69
Opened 2024-03-05 20:10 UTC by tbolt

2024-03-06 18:05 UTC, tbolt reviewed
Looks good to me. @sublettk or @ian-sawyer can you do a final approval for this?

2024-03-07 20:37 UTC, sublettk requested changes
LGTM!

2024-03-07 20:37 UTC, sublettk commented on src/screens/Submissions.tsx
> +    }
Let's keep the original implementation.

2024-03-07 20:46 UTC, ZacharyRizer commented on src/screens/Submissions.tsx
> +    }
Switched back.

2024-03-07 20:46 UTC, sublettk approved these changes

2024-03-08 18:51 UTC, merged